server:
  port: 8888


spring:
  application:
    name: config-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/anstn1993/spring-cloud-config.git
          default-label: main
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
